app = "telegram-bot--88-aq"
primary_region = "jnb"

[build]
dockerfile = "Dockerfile"

[processes]
app = ""

[mounts]
source = "telegram_bot_data"
destination = "/data"
initial_size = "1gb"

[[vm]]
cpu_kind = "shared"
cpus = 1
memory = "1gb"
memory_mb = 1024

[http_service]
internal_port = 8080
auto_start_machines = true
auto_stop_machines = false
min_machines_running = 1